apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: perplexica-frontend
  name: perplexica-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: perplexica-frontend
  template:
    metadata:
      labels:
        io.kompose.service: perplexica-frontend
    spec:
      containers:
        - image: ghcr.io/denverdino/perplexica-frontend:c09706fef7f04efd98c28d88bca3055c8fe2acd4
          name: perplexica-frontend
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
