apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: searxng
  name: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: searxng
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: searxng
    spec:
      containers:
        - image: docker.io/searxng/searxng:latest
          name: searxng
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/searxng
              name: searxng-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: searxng-cm0
          name: searxng-cm0
