name: Build and push images to ghcr.io

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push-images:
    
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push frontend image'
        uses: docker/build-push-action@v5
        with:
          push: true
          file: app.dockerfile
          tags: ghcr.io/denverdino/perplexica-frontend:${{ github.sha }}
      
      - name: 'Build and push backend image'
        uses: docker/build-push-action@v5
        with:
          push: true
          file: backend.dockerfile
          tags: ghcr.io/denverdino/perplexica-backend:${{ github.sha }}

